{{- if .Values.serviceMonitor.create }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "rafterFrontMatterService.serviceMonitorName" . }}
  labels:
    prometheus: monitoring
    app.kubernetes.io/name: {{ include "rafterFrontMatterService.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "rafterFrontMatterService.chart" . }}
  {{- if .Values.serviceMonitor.labels }}
    {{ include "rafterFrontMatterService.tplValue" ( dict "value" .Values.metrics.serviceMonitor.labels "context" . ) | nindent 4 }}
  {{- end }}
  {{- if .Values.serviceMonitor.annotations }}
  annotations:
    {{ include "rafterFrontMatterService.tplValue" ( dict "value" .Values.metrics.serviceMonitor.annotations "context" . ) | nindent 4 }}
  {{- end }}
spec:
  endpoints:
    - interval: {{ .Values.serviceMonitor.scrapeInterval }}
      port: {{ .Values.service.port.name }}
      path: /metrics
      metricRelabelings:
      - sourceLabels: [ __name__ ]
        regex: ^(go_goroutines|go_memstats_alloc_bytes|go_memstats_heap_alloc_bytes|go_memstats_heap_inuse_bytes|go_memstats_heap_sys_bytes|go_memstats_stack_inuse_bytes|process_cpu_seconds_total|process_max_fds|process_open_fds|process_resident_memory_bytes|process_start_time_seconds|process_virtual_memory_bytes)$
        action: keep
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "rafterFrontMatterService.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
