---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: kyma-system
  name: {{ template "event-publish-service.fullname" . }}
  labels:
{{ include "event-publish-service.labels.standard" . | indent 4 }}
    prometheus: monitoring
spec:
  selector:
    matchLabels:
{{ include "event-publish-service.labels.selectors" . | indent 6 }}
  endpoints:
  - port: http-metrics
{{- if .Values.monitoring.scrapeInterval }}
    interval: {{ .Values.monitoring.scrapeInterval }}
{{- end }}
    metricRelabelings:
    - sourceLabels: [ __name__ ]
      regex: ^(go_goroutines|go_memstats_alloc_bytes|go_memstats_heap_alloc_bytes|go_memstats_heap_inuse_bytes|go_memstats_heap_sys_bytes|go_memstats_stack_inuse_bytes|process_cpu_seconds_total|process_max_fds|process_open_fds|process_resident_memory_bytes|process_start_time_seconds|process_virtual_memory_bytes|total_published_messages)$
      action: keep
  namespaceSelector:
    any: true
